### ISSUE TITLE
how to focus

### ISSUE THREAD

**Issue by kings1990** [aspnet/jquery-validation-unobtrusive#22] opened 2016-01-12 06:51 UTC
I can't auto focus the error input element,why ?
in my jquery.valdate.js ,the property focusInvalid=true
 what's my mistake?

**Comment by Eilon** [comment] 2016-01-27 01:32
@kings1990 can you show more code? Where did you set that? It would be best if you can upload a simplified app to a GitHub repo and we can take a look.

**Comment by kings1990** [comment] 2016-01-27 01:51
1.Include the js
<script src="/static/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/jquery/jquery.validate.js"></script>
<script type="text/javascript" src="/static/jquery/jquery.validate.regular.js"></script>
<script type="text/javascript" src="/static/jquery/jquery.validate.messages_cn.js"></script>
<script type="text/javascript" src="/static/jquery/jquery.validate.unobtrusive.js"></script>

2.see my jsp
<%@ page language="java" import="java.util.*" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en">
<head>
<script type="text/javascript" src="/static/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/jquery/jquery.validate.js"></script>
<script type="text/javascript" src="/static/jquery/jquery.validate.unobtrusive.js"></script>
<script type="text/javascript" src="/static/jquery/jquery.validate.messages_cn.js"></script>

<link rel="stylesheet" href="/static/bootstrap/css/bootstrap.css" />
<link rel="stylesheet" href="/static/bootstrap/css/font-awesome.css" />
<link rel="stylesheet" href="/static/ace/css/ace.css" class="ace-main-stylesheet" id="main-ace-style" />
<link rel="stylesheet" href="/static/ace/css/ace-fonts.css" />
<link rel="stylesheet" href="/static/crm/css/crm.css" />
</head>
<body>
	<div class="container">
		<div class="row">
			<form action="" class="form-horizontal" id="formId">
				<div class="form-group" id="div1">
					<label class="control-label col-md-2" for="tId">Domain Account:</label>
					<div class="col-md-5">
						<div>
							<input class="col-xs-10 col-sm-10" type="text" id="tId" name="tId" data-val-email="email is invalid" data-val="true"
								data-val-required />
						</div>
						<div class="text-danger clearfix" data-valmsg-for="tId" data-valmsg-replace="true"></div>
					</div>
				</div>
				<input type="button" value="add" id="add">
				<input type="button" value="submit" id="submit"/>
			</form>
		</div>
	</div>
</body>
</html>

3.it seems it can't auto focus the error element
 i search the query.validate.js and i find the default setting 
![16de3a02-5f8d-4ef8-82f3-69bf14b53a89](https://cloud.githubusercontent.com/assets/8969637/12601310/199a19c4-c4db-11e5-94c7-205d23556701.png)
![55](https://cloud.githubusercontent.com/assets/8969637/12601370/7bbef660-c4db-11e5-8a35-9e8ec7f0faad.gif)

**Comment by kings1990** [comment] 2016-01-29 01:05
could you help me resolve it? @Eilon

**Comment by Eilon** [comment] 2016-02-03 23:46
@ryanbrandenburg as with the other issue you were looking at, this one might also involve identifying whether this is our code (Unobtrusive) or just basic jQuery Validate.

**Comment by Eilon** [comment] 2016-02-03 23:47
Also note that the original code in the repro is using JSP (Java), but the issue is client side so the server tech shouldn't matter.

**Comment by ryanbrandenburg** [comment] 2016-02-04 01:03
Here is a bare bones working example of your code:
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>
<body>
    <div class="container body-content">
        @RenderBody()
    </div>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>

    <form action="" class="form-horizontal" id="formId">
        <div class="form-group" id="div1">
            <label class="control-label col-md-2" for="tId">Domain Account:</label>
            <div class="col-md-5">
                <div>
                    <input class="col-xs-10 col-sm-10" type="text" id="tId" name="tId" data-val-email="email is invalid"
                           data-val="true" data-val-required />
                </div>
                <div class="text-danger clearfix" data-valmsg-for="tId" data-valmsg-replace="true"></div>
            </div>
        </div>
        <input type="button" value="add" id="add" />
        <input type="button" value="submit" id="submit" />
    </form>

    <script type="text/javascript">
        $(document).ready(function () {
            $('#submit').click(function () {
                $('#formId').submit();
            });
        });
    </script>
</body>
</html>
```

The important part here is that you must submit the form. Focus will not happen if you just do "valid()". And of note here is that that is a property of jquery.validate.js, not of this repo.

Does that clear things up for you? If not please post a minimum reproduction repo.

**Comment by ryanbrandenburg** [comment] 2016-02-08 20:09
I'm going to close this one as "invalid". If you have more information then feel free to re-open it with that new info, otherwise I think the above should take care of you.

**Closed by ryanbrandenburg** 2016-02-08 20:09 UTC
Labels: invalid, investigate
