### ISSUE TITLE
WCAG validation failure for aria described by after fixing errors on forms.

### ISSUE THREAD

**Issue by luisluix** [aspnet/jquery-validation-unobtrusive#75] opened 2018-02-14 15:46 UTC
https://dotnetfiddle.net/HiDCu5

Step 1; click submit
Step 2: put something in textbox 1
Step 3: inspect elements

If you check the "aria-described by" of the elements, input1 aria-described by points to "inputtext-error", but since we already fixed the error, the element with the "inputtext-error" ID no longer exists. This is what is causing the WCAG error. When we do step 2, aria-described by on input1 should be removed as well.

**Comment by mkArtakMSFT** [comment] 2018-02-16 17:56
@jbagga, can you please look into this? Thanks!

**Comment by jbagga** [comment] 2018-03-13 16:32
Thanks @luisluix 
This seems to be a dupe of https://github.com/jquery-validation/jquery-validation/issues/2094 as you are aware of already :)
Closing for now.

**Closed by jbagga** 2018-03-13 16:32 UTC
Labels: cost: M, investigate
