### ISSUE TITLE
jquery-validation-unobtrusive npm package missing min version

### ISSUE THREAD

**Issue by FanrayMedia** [aspnet/jquery-validation-unobtrusive#71] opened 2017-10-09 21:39 UTC
Installing npm package https://www.npmjs.com/package/jquery-validation-unobtrusive will only give you jquery.validate.unobtrusive.js, it's missing the min version.  Should it be like jquery-validation lib when installed it gives you a /dist folder which contains both min and un-min-ed version?

**Comment by mkArtakMSFT** [comment] 2018-02-12 22:46
Thanks for reporting this issue, @FanrayMedia.
@kichalla, can you please look into this when you'll be back? Thanks!

**Comment by mkArtakMSFT** [comment] 2018-02-12 22:48
Actually, it seems this is a dupe of https://github.com/aspnet/jquery-validation-unobtrusive/issues/66. Closing this issue.

**Closed by mkArtakMSFT** 2018-02-12 22:48 UTC
Labels: investigate
